version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 8099:80
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 9090:9000
    links:
      - db
    environment:
      - DB_PORT=5432
      - DB_HOST=db
      - DB_CONNECTION=pgsql
  db:
    image: postgres:9-alpine
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
